<?php

namespace AppBundle\Repository;

/**
 * AntenneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntenneRepository extends \Doctrine\ORM\EntityRepository
{
}
