<?php

namespace AppBundle\Repository;

/**
 * CourrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourrierRepository extends \Doctrine\ORM\EntityRepository
{
}
