<?php

namespace AppBundle\Repository;

/**
 * EntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
