<?php

namespace AppBundle\Repository;

/**
 * PayeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayeRepository extends \Doctrine\ORM\EntityRepository
{
}
