<?php

namespace AppBundle\Repository;

/**
 * StatStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatStockRepository extends \Doctrine\ORM\EntityRepository
{
}
