<?php

namespace AppBundle\Repository;

/**
 * StockProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
